#!/usr/bin/env node
/**
 * Generate firmware/src/schedule_data.h from data/schedule.json.
 *
 * The ESP32 firmware has no filesystem-JSON dependency: the schedule is
 * baked into flash as compact C tables. This mirrors the Clawdmeter pattern
 * of generating C headers from source assets (fonts, splash animations).
 *
 * When NJ Transit updates its GTFS feed:
 *   npm run build:schedule      # rewrites data/schedule.json  (in family-dash root)
 *   node tools/gen_schedule.mjs # regenerates the header
 *   ./flash-mac.sh              # reflash
 *
 * Usage:  node tools/gen_schedule.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, "..");
const SRC = join(ROOT, "data", "schedule.json");
const OUT = join(ROOT, "firmware", "src", "schedule_data.h");

// The four boards the display shows (origin -> dest by GTFS stop_id),
// mirrored from app/api/departures/route.ts.
const BOARDS = [
  { origin: "92", dest: "105" }, // Morristown -> New York
  { origin: "92", dest: "63" }, // Morristown -> Hoboken
  {
    origin: "18",
    dest: "105", // Bernardsville -> New York
    note: "Few one-seat rides — most NY trips transfer at Summit.",
  },
  { origin: "18", dest: "63" }, // Bernardsville -> Hoboken
];

/** Collapse to plain ASCII so the GFX bitmap fonts render every glyph. */
function ascii(s) {
  return String(s ?? "")
    .replace(/[‒-―−]/g, "-") // dashes → hyphen
    .replace(/[‘’‛]/g, "'") // curly single quotes
    .replace(/[“”]/g, '"') // curly double quotes
    .replace(/…/g, "...") // ellipsis
    .replace(/·/g, "-") // middle dot
    .replace(/[^\x20-\x7E]/g, "?"); // anything else left
}

/** C string literal (already ASCII-sanitized). */
function cstr(s) {
  return '"' + ascii(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"') + '"';
}

function gtfsSeconds(t) {
  const [h, m, s] = String(t).split(":").map(Number);
  return h * 3600 + m * 60 + (s || 0);
}

function main() {
  const sched = JSON.parse(readFileSync(SRC, "utf8"));

  // --- Stations: origins then destinations, stable index by insertion. -----
  const stationName = { ...sched.origins, ...sched.destinations };
  const stationIds = Object.keys(stationName);
  const stationIdx = new Map(stationIds.map((id, i) => [id, i]));

  // --- Routes ---------------------------------------------------------------
  const routeIds = Object.keys(sched.routes);
  const routeIdx = new Map(routeIds.map((id, i) => [id, i]));

  // --- Services (calendar) --------------------------------------------------
  const serviceIds = Object.keys(sched.calendar);
  const serviceIdx = new Map(serviceIds.map((id, i) => [id, i]));

  // --- Headsigns (deduped) --------------------------------------------------
  const headsigns = [];
  const headsignIdx = new Map();
  const internHeadsign = (h) => {
    const key = ascii(h);
    if (!headsignIdx.has(key)) {
      headsignIdx.set(key, headsigns.length);
      headsigns.push(key);
    }
    return headsignIdx.get(key);
  };

  // --- Trips ----------------------------------------------------------------
  const trips = sched.trips.map((t) => ({
    origin: stationIdx.get(t.origin),
    dest: stationIdx.get(t.dest),
    route: routeIdx.get(t.route),
    service: serviceIdx.get(t.service),
    depSec: gtfsSeconds(t.dep),
    arrSec: gtfsSeconds(t.arr),
    headsign: internHeadsign(t.headsign),
  }));

  // Sanity: every field resolved.
  for (const [i, t] of trips.entries()) {
    for (const k of ["origin", "dest", "route", "service"]) {
      if (t[k] === undefined) throw new Error(`trip ${i}: unresolved ${k}`);
    }
  }

  // --- Emit -----------------------------------------------------------------
  const L = [];
  L.push("// AUTO-GENERATED by tools/gen_schedule.mjs — DO NOT EDIT.");
  L.push(`// Source: data/schedule.json (generated ${sched.generatedAt})`);
  L.push("#pragma once");
  L.push("#include <stdint.h>");
  L.push("");
  L.push(`#define SCHED_GENERATED_AT ${cstr(sched.generatedAt)}`);
  L.push("");

  L.push("struct SchedRoute { const char* name; const char* shortName; };");
  L.push("struct SchedService { const uint32_t* dates; uint16_t count; };");
  L.push("struct SchedTrip {");
  L.push("  uint8_t origin, dest, route, service, headsign;");
  L.push("  uint32_t depSec, arrSec;");
  L.push("};");
  L.push("struct SchedBoard { uint8_t origin; uint8_t dest; const char* note; };");
  L.push("");

  // Stations
  L.push(`#define SCHED_NUM_STATIONS ${stationIds.length}`);
  L.push("static const char* const SCHED_STATION_NAME[SCHED_NUM_STATIONS] = {");
  for (const id of stationIds) L.push(`  ${cstr(stationName[id])}, // ${id}`);
  L.push("};");
  L.push("");

  // Routes
  L.push(`#define SCHED_NUM_ROUTES ${routeIds.length}`);
  L.push("static const SchedRoute SCHED_ROUTE[SCHED_NUM_ROUTES] = {");
  for (const id of routeIds) {
    const r = sched.routes[id];
    L.push(`  { ${cstr(r.name)}, ${cstr(r.short)} }, // ${id}`);
  }
  L.push("};");
  L.push("");

  // Headsigns
  L.push(`#define SCHED_NUM_HEADSIGNS ${headsigns.length}`);
  L.push("static const char* const SCHED_HEADSIGN[SCHED_NUM_HEADSIGNS] = {");
  for (const h of headsigns) L.push(`  ${cstr(h)},`);
  L.push("};");
  L.push("");

  // Service date tables
  serviceIds.forEach((id, i) => {
    const dates = [...sched.calendar[id]]
      .map((d) => Number(d))
      .sort((a, b) => a - b);
    L.push(
      `static const uint32_t SCHED_SVC${i}_DATES[${dates.length}] = { ${dates.join(
        ", "
      )} }; // service ${id}`
    );
  });
  L.push("");
  L.push(`#define SCHED_NUM_SERVICES ${serviceIds.length}`);
  L.push("static const SchedService SCHED_SERVICE[SCHED_NUM_SERVICES] = {");
  serviceIds.forEach((id, i) => {
    const n = sched.calendar[id].length;
    L.push(`  { SCHED_SVC${i}_DATES, ${n} }, // ${id}`);
  });
  L.push("};");
  L.push("");

  // Trips
  L.push(`#define SCHED_NUM_TRIPS ${trips.length}`);
  L.push("static const SchedTrip SCHED_TRIP[SCHED_NUM_TRIPS] = {");
  for (const t of trips) {
    L.push(
      `  { ${t.origin}, ${t.dest}, ${t.route}, ${t.service}, ${t.headsign}, ${t.depSec}, ${t.arrSec} },`
    );
  }
  L.push("};");
  L.push("");

  // Boards
  L.push(`#define SCHED_NUM_BOARDS ${BOARDS.length}`);
  L.push("static const SchedBoard SCHED_BOARD[SCHED_NUM_BOARDS] = {");
  for (const b of BOARDS) {
    const o = stationIdx.get(b.origin);
    const d = stationIdx.get(b.dest);
    if (o === undefined || d === undefined) {
      throw new Error(`board ${b.origin}->${b.dest}: unknown station id`);
    }
    L.push(`  { ${o}, ${d}, ${b.note ? cstr(b.note) : "nullptr"} },`);
  }
  L.push("};");
  L.push("");

  writeFileSync(OUT, L.join("\n") + "\n");
  console.log(
    `Wrote ${OUT}\n  ${trips.length} trips, ${serviceIds.length} services, ` +
      `${routeIds.length} routes, ${headsigns.length} headsigns, ` +
      `${stationIds.length} stations, ${BOARDS.length} boards.`
  );
}

main();
